package QBO;

/**
 * Created by gl on 1/2/16.
 */
public enum FailType {
    UNEXPECTED_FAIL_CASE,

    REQUIRED_PARAMS_NOT_EXIST, USB_BUTTON_NOT_CONNECT, BARCODE_SCANNER_NOT_CONNECT, JLINK_NOT_CONNECT,

    BARCODE_SCAN_FAIL, BARCODE_MAPPING_FAIL, READ_MCU_SN_FAIL, CALL_FIRMWARE_GENERATOR_FAIL, FIRMWARE_BURNING_IS_INTERRUPTED, SAVE_TO_PROD_DB_FAIL, CLEAN_FAIL,
}
